---
- name: check if docker is installed
  become: true
  command: docker --version
  register: docker_version
  ignore_errors: true

- name: Include node exporter docker task if docker is installed
  include_tasks: node-docker.yaml
  when: docker_version.rc == 0

- name: Include node exporter service tasks if docker is not installed
  include_tasks: node-service.yaml
  when: docker_version.rc != 0
