---
- name: Install Docker Compose
  become: true
  apt:
    name: docker-compose
    state: present

- name: Copy Docker Compose file
  copy:
    src: ../files/docker-compose.yaml
    dest: /opt/node-exporter/docker-compose.yml

- name: Start Node Exporter
  become: true
  command: docker-compose up -d
  args:
    chdir: /opt/node-exporter
