---
- name: Download Node Exporter
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: "/tmp/node_exporter.tar.gz"

- name: Extract Node Exporter
  unarchive:
    src: "/tmp/node_exporter.tar.gz"
    dest: "/opt/node_exporter"
    remote_src: true
    copy: false
    creates: "/opt/node_exporter/node_exporter-{{ node_exporter_version }}.linux-amd64"


- name: Create node_exporter group
  group:
    name: "{{ node_exporter_group }}"
    state: present

- name: Create node_exporter user and group
  user:
    name: "{{ node_exporter_user }}"
    state: present
    groups: "{{ node_exporter_group }}"



- name: Install Node Exporter systemd service
  systemd:
    name: node_exporter
    enabled: yes
    state: started
    daemon_reload: yes
    user: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
    executable: /opt/node_exporter/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter
    args:
      - "--web.listen-address=:{{ node_exporter_port }}"
