---
- name: Copy Docker Compose file
  copy:
    src: ../files/docker-compose.yaml
    dest: "{{ node_exporter_dest }}/docker-compose.yml"

- name: Start Node Exporter
  become: true
  command: docker-compose up -d
  args:
    chdir: "{{ node_exporter_dest }}"
