version: "3.9"
services:
  sm-exporter:
    image: docker-hub.tip.co.ir/targoman/nvidia-exporter:latest
    pull_policy: missing
    labels:
      com.example.description: "Prometheus SM Exproter Container"
    ports:
      - "9000:9000"
    container_name: sm-exporter-exporter
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

  gpu-exporter:
    image: docker.tip.co.ir/targoman/gpu-exporter:latest
    pull_policy: missing
    labels:
      com.example.description: "Prometheus GPU Exporter Container"
    ports:
      - "9835:9835"
    volumes:
      - "/usr/lib64/libnvidia-ml.so:/usr/lib64/libnvidia-ml.so"
      - "/usr/lib64/libnvidia-ml.so.1:/usr/lib64/libnvidia-ml.so.1"
      - "/usr/bin/nvidia-smi:/usr/bin/nvidia-smi"
    devices:
      - "/dev/nvidiactl:/dev/nvidiactl"
      - "/dev/nvidia0:/dev/nvidia0"
      - "/dev/nvidia1:/dev/nvidia1"
    container_name: gpu-exporter
    deploy:
      restart_policy:
        condition: unless-stopped
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
