version: "3.9"
services:
  sm-exporter:
    image: registry.example.com/targoman/nvidia-exporter:v1.0.0
    pull_policy: if-not-present
    labels:
      com.example.description: "Prometheus SM Exporter Container"
    ports:
      - "9000:9000"
    container_name: sm-exporter
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

  gpu-exporter:
    image: registry.example.com/targoman/gpu-exporter:v1.0.0
    pull_policy: if-not-present
    labels:
      com.example.description: "Prometheus GPU Exporter Container"
    ports:
      - "9835:9835"
    volumes:
      - gpu-exporter-data:/data
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_REQUIRE_CUDA=cuda>=10.1
    secrets:
      - gpu-exporter-secrets
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9835/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
    container_name: gpu-exporter
    deploy:
      restart_policy:
        condition: unless-stopped
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
secrets:
  gpu-exporter-secrets:
    external: true
volumes:
  gpu-exporter-data:
