---
- name: Check if Docker Compose binary already exists
  stat:
    path: "{{ docker_compose_dest_file }}"
  register: compose_file

- name: Download Docker Compose binary
  get_url:
    url: "{{ docker_compose_download_url }}"
    dest: "{{ docker_compose_dest_file }}"
    mode: '0755'
  when: not compose_file.stat.exists

- name: Verify Docker Compose installation
  shell: "docker-compose --version"
  register: docker_compose_version_output
  changed_when: false
  failed_when: docker_compose_version_output.rc not in [0, 1]

- name: Print Docker Compose version
  debug:
    msg: "Installed Docker Compose version is {{ docker_compose_version_output.stdout }}."
