galaxy_info:
  author: Sms-RK
  description: Ansible role for running MySQL Prometheus exporter Docker image.
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal
