---
# defaults file for node-exporter
node_exporter_version: "1.5.0"
node_exporter_user: "node_exporter"
node_exporter_group: "node_exporter"
node_exporter_port: "9100"
node_exporter_dest: "/opt/node-exporter"
